const interestGroups = [
    {
        name: 'Self-care',
        code: 1,
        interests: [
            { description: '💫 Astrology', code: 1 },
            { description: '💎 Crystals', code: 2 },
            { description: '💬 Deep chats', code: 3 },
            { description: '✍ Journaling', code: 4 },
            { description: '🧠 Mindfulness', code: 5 },
            { description: '🥦 Nutrition', code: 6 },
            { description: '💤 Sleeping well', code: 7 },
            { description: '💛 Therapy', code: 8 },
            { description: '🏞 Time offline', code: 9 }
        ]
    },
    {
        name: 'Sports & Athletics',
        code: 2,
        interests: [
            { description: '🎽 Athletics', code: 10 },
            { description: '🏸 Badminton', code: 11 },
            { description: '⚾ Baseball', code: 12 },
            { description: '🏀 Basketball', code: 13 },
            { description: '🎳 Bowling', code: 14 },
            { description: '🥊 Boxing', code: 15 },
            { description: '🏏 Cricket', code: 16 },
            { description: '🚲 Cycling', code: 17 },
            { description: '🏈 Football', code: 18 },
            { description: '🏎 Go karting', code: 19 },
            { description: '⛳ Golf', code: 20 },
            { description: '🏋️‍♀️ Gym', code: 21 },
            { description: '🤸‍♀️ Gymnastics', code: 22 },
            { description: '🤾‍♀️ Handball', code: 23 },
            { description: '🏒 Hockey', code: 24 },
            { description: '🏇 Horse riding', code: 25 },
            { description: '⛸ Ice skating', code: 26 },
            { description: '🥍 Lacrosse', code: 27 },
            { description: '🥋 Martial arts', code: 28 },
            { description: '✌ Meditation', code: 29 },
            { description: '🏍 Motorbiking', code: 30 },
            { description: '🏐 Netball', code: 31 },
            { description: '🏓 Padel', code: 32 },
            { description: '🏓 Pickleball', code: 33 },
            { description: '🤸‍♀️ Pilates', code: 34 },
            { description: '🏓 Ping pong', code: 35 },
            { description: '🧗‍♀️ Rock climbing', code: 36 },
            { description: '🚣‍♀️ Rowing', code: 37 },
            { description: '🏉 Rugby', code: 38 },
            { description: '👟 Running', code: 39 },
            { description: '⛵ Sailing', code: 40 },
            { description: '🤿 Scuba diving', code: 41 },
            { description: '🛹 Skateboarding', code: 42 },
            { description: '🎿 Skiing', code: 43 },
            { description: '🏂 Snowboarding', code: 44 },
            { description: '⚽ Soccer', code: 45 },
            { description: '🥎 Softball', code: 46 },
            { description: '🏓 Squash', code: 47 },
            { description: '🌊 Surfing', code: 48 },
            { description: '🏊‍♀️ Swimming', code: 49 },
            { description: '🎾 Tennis', code: 50 },
            { description: '🏐 Volleyball', code: 51 },
            { description: '🧘‍♀️ Yoga', code: 52 }
        ]
    },
    {
        name: 'Creativity',
        code: 12,
        interests: [
            { description: '🎨 Art', code: 53 },
            { description: '🧷 Crafts', code: 54 },
            { description: '💃 Dancing', code: 55 },
            { description: '✏ Design', code: 56 },
            { description: '🧥 Fashion', code: 57 },
            { description: '💄 Make up', code: 58 },
            { description: '📼 Making videos', code: 59 },
            { description: '💅 Nail art', code: 60 },
            { description: '📷 Photography', code: 61 },
            { description: '🏺 Pottery', code: 62 },
            { description: '🎤 Singing', code: 63 },
            { description: '📝 Writing', code: 64 }
        ]
    },
    {
        name: 'Going out',
        code: 13,
        interests: [
            { description: '🍻 Bars', code: 65 },
            { description: '☕ Cafe-hopping', code: 66 },
            { description: '🎟 Concerts', code: 67 },
            { description: '👑 Drag shows', code: 68 },
            { description: '🎊 Festivals', code: 69 },
            { description: '🎭 Improv', code: 70 },
            { description: '🎤 Karaoke', code: 71 },
            { description: '🎉 LGBTQ+ nightlife', code: 72 },
            { description: '🏛 Museums & galleries', code: 73 },
            { description: '🕺 Night clubs', code: 74 },
            { description: '🎙 Stand up', code: 75 },
            { description: '🎭 Theatre', code: 76 }
        ]
    },
    {
        name: 'Staying in',
        code: 3,
        interests: [
            { description: '🤖 AI', code: 77 },
            { description: '🍰 Baking', code: 78 },
            { description: '🎲 Board games', code: 79 },
            { description: '♟ Chess', code: 80 },
            { description: '🍳 Cooking', code: 81 },
            { description: '🌱 Gardening', code: 82 },
            { description: '🎙 Podcasts', code: 83 },
            { description: '💻 Programming', code: 84 },
            { description: '📚 Reading', code: 85 },
            { description: '🎮 Video games', code: 86 }
        ]
    },
    {
        name: 'Film and TV',
        code: 4,
        interests: [
            { description: '📺 Action & adventure', code: 87 },
            { description: '📺 Animated', code: 88 },
            { description: '📺 Anime', code: 89 },
            { description: '📺 Bollywood', code: 90 },
            { description: '📺 Comedy', code: 91 },
            { description: '📺 Cooking shows', code: 92 },
            { description: '📺 Crime', code: 93 },
            { description: '📺 Documentaries', code: 94 },
            { description: '📺 Drama', code: 95 },
            { description: '📺 Fantasy', code: 96 },
            { description: '📺 Game shows', code: 97 },
            { description: '📺 Horror', code: 98 },
            { description: '📺 Indie', code: 99 },
            { description: '📺 K-drama', code: 100 },
            { description: '📺 Mystery', code: 101 },
            { description: '📺 Reality shows', code: 102 },
            { description: '📺 Rom-com', code: 103 },
            { description: '📺 Romance', code: 104 },
            { description: '📺 Sci-fi', code: 105 },
            { description: '📺 Superhero', code: 106 },
            { description: '📺 Thriller', code: 107 },
            { description: '📺 True crime', code: 108 }
        ]
    },
    {
        name: 'Reading',
        code: 5,
        interests: [
            { description: '📚 Action & adventure', code: 109 },
            { description: '📚 Biographies', code: 110 },
            { description: '📚 Classics', code: 111 },
            { description: '📚 Comedy', code: 112 },
            { description: '📚 Comic books', code: 113 },
            { description: '📚 Crime', code: 114 },
            { description: '📚 Fantasy', code: 115 },
            { description: '📚 History', code: 116 },
            { description: '📚 Horror', code: 117 },
            { description: '📚 Manga', code: 118 },
            { description: '📚 Mystery', code: 119 },
            { description: '📚 Philosophy', code: 120 },
            { description: '📚 Poetry', code: 121 },
            { description: '📚 Psychology', code: 122 },
            { description: '📚 Romance', code: 123 },
            { description: '📚 Science', code: 124 },
            { description: '📚 Sci-fi', code: 125 },
            { description: '📚 Thriller', code: 126 }
        ]
    },
    {
        name: 'Music',
        code: 11,
        interests: [
            { description: '🎵 Afrobeats', code: 210 },
            { description: '🎵 Alternative', code: 127 },
            { description: '🎵 Blues', code: 128 },
            { description: '🎵 Classical', code: 129 },
            { description: '🎵 Country', code: 130 },
            { description: '🎵 Desi', code: 131 },
            { description: '🎵 EDM', code: 132 },
            { description: '🎵 Electronic', code: 133 },
            { description: '🎵 Folk & acoustic', code: 134 },
            { description: '🎵 Funk', code: 135 },
            { description: '🎵 Hip hop', code: 136 },
            { description: '🎵 House', code: 137 },
            { description: '🎵 Indie', code: 138 },
            { description: '🎵 Jazz', code: 139 },
            { description: '🎵 K-pop', code: 140 },
            { description: '🎵 Latin', code: 141 },
            { description: '🎵 Metal', code: 142 },
            { description: '🎵 Pop', code: 143 },
            { description: '🎵 Punk', code: 144 },
            { description: '🎵 R&B', code: 145 },
            { description: '🎵 Rap', code: 146 },
            { description: '🎵 Reggae', code: 147 },
            { description: '🎵 Rock', code: 148 },
            { description: '🎵 Soul', code: 149 },
            { description: '🎵 Techno', code: 150 }
        ]
    },
    {
        name: 'Food and drink',
        code: 6,
        interests: [
            { description: '🍺 Beer', code: 151 },
            { description: '🍛 Biriyani', code: 152 },
            { description: '🧋 Boba tea', code: 153 },
            { description: '☕ Coffee', code: 154 },
            { description: '🌮 Foodie', code: 155 },
            { description: '🍸 Gin', code: 156 },
            { description: '🍕 Pizza', code: 157 },
            { description: '🥑 Plant-based', code: 158 },
            { description: '🍟 Poutine', code: 159 },
            { description: '🍣 Sushi', code: 160 },
            { description: '🍫 Sweet tooth', code: 161 },
            { description: '🥡 Takeout', code: 162 },
            { description: '🍵 Tea', code: 163 },
            { description: '🌱 Vegan', code: 164 },
            { description: '🥦 Vegetarian', code: 165 },
            { description: '🥃 Whisky', code: 166 },
            { description: '🍷 Wine', code: 167 }
        ]
    },
    {
        name: 'Travelling',
        code: 7,
        interests: [
            { description: '🎒 Backpacking', code: 168 },
            { description: '🏖 Beaches', code: 169 },
            { description: '🏕 Camping', code: 170 },
            { description: '🌆 City breaks', code: 171 },
            { description: '🎣 Fishing trips', code: 172 },
            { description: '⛰ Hiking trips', code: 173 },
            { description: '🛣 Road trips', code: 174 },
            { description: '🛀 Spa weekends', code: 175 },
            { description: '🏡 Staycations', code: 176 },
            { description: '❄ Winter sports', code: 177 }
        ]
    },
    {
        name: 'Pets',
        code: 8,
        interests: [
            { description: '🐦 Birds', code: 178 },
            { description: '🐱 Cats', code: 179 },
            { description: '🐶 Dogs', code: 180 },
            { description: '🐟 Fish', code: 181 },
            { description: '🦎 Lizards', code: 182 },
            { description: '🐇 Rabbits', code: 183 },
            { description: '🐍 Snakes', code: 184 },
            { description: '🐢 Turtles', code: 185 }
        ]
    },
    {
        name: 'Personality and traits',
        code: 9,
        interests: [
            { description: '🚀 Ambition', code: 186 },
            { description: '🏆 Being active', code: 187 },
            { description: '❤ Being family-oriented', code: 188 },
            { description: '🧠 Being open-minded', code: 189 },
            { description: '💘 Being romantic', code: 190 },
            { description: '😎 Confidence', code: 191 },
            { description: '🖋 Creativity', code: 192 },
            { description: '💙 Empathy', code: 193 },
            { description: '🎓 Intelligence', code: 194 },
            { description: '☀ Positivity', code: 195 },
            { description: '🧐 Self-awareness', code: 196 },
            { description: '⛰ Sense of adventure', code: 197 },
            { description: '😂 Sense of humour', code: 198 },
            { description: '👁 Social awareness', code: 199 }
        ]
    },
    {
        name: 'Values and allyship',
        code: 10,
        interests: [
            { description: '🖤 Black Lives Matter', code: 200 },
            { description: '🚫 End religious hate', code: 201 },
            { description: '🌎 Environmentalism', code: 202 },
            { description: '💛 Feminism', code: 203 },
            { description: '📜 Human rights', code: 204 },
            { description: '🏳‍🌈 LGBTQ+ rights', code: 205 },
            { description: '➕ Sex positivity', code: 206 },
            { description: '🚫 Stop Asian Hate', code: 207 },
            { description: '⚧️ Trans rights', code: 208 },
            { description: '☑ Voter rights', code: 209 }
        ]
    }
];

export default interestGroups;